### ISSUE TITLE
Ordering Veeam licences

### ISSUE THREAD

**Issue by syllamine** [ibm-cloud-docs/cloud-infrastructure#1]
Hi

I want to order a veeam licence, but the mail (veeam@ibm.com) does not work.
Someone can help me please.

Regards

**Comment by bpersich** [comment]
@syllamine . You can email jordan.shamir@ibm.com to order Veeam licenses. We are working on a fix and will keep this issue open until it is complete.

thank you.

**Comment by bpersich** [comment]
This is fixed. The Veeam ordering email address is now veeamvpc@us.ibm.com
