### ISSUE TITLE
Adding intel

### ISSUE THREAD

**Issue by go-davidng** [ibm-cloud-docs/cloud-infrastructure#12]
@katylak we need to add `Intel Xeon` somewhere in the document for Intel NRE funding.  I was thinking of adding to the first sentence.

Terraform on IBM Cloud® enables predictable and consistent provisioning of IBM Cloud VPC infrastructure resources so that you can rapidly build complex, cloud environments with Intel Xeon.

What do you think?  I'm open if there is a better place and/or way of adding it.

**Comment by DLM-IBM** [comment]
Thank you for the comment. This issue is being investigated and will be resolved by the documentation team.
