### ISSUE TITLE
Is the limit 99GB or 250GB?

### ISSUE THREAD

**Issue by itsophie** [ibm-cloud-docs/cloud-infrastructure#15]
The statement in this document: https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-migrating-images-vpc

_The boot volume (primary vHDD) doesn't exceed 99 GB_

differs with this document: https://cloud.ibm.com/docs/vpc?topic=vpc-planning-custom-images

which says:
_Size doesn't exceed 250 GB
Size isn't less than 10 GB, images less than 10 GB are rounded up to 10 GB_

**Comment by DLM-IBM** [comment]
Thank you for the comment. This issue is being investigated and will be resolved by the documentation team.
