### ISSUE TITLE
App IP out of range

### ISSUE THREAD

**Issue by alessandrofaraotti** [ibm-cloud-docs/cloud-infrastructure#17]
I have checked the IP address of my app on IBM Cloud in Frankfurt and it appears to be out of the range 149.81.118.0/23,
may you double check?
Cheers
A.

**Comment by Lauren-Fulcher** [comment]
Hello @alessandrofaraotti, sorry for the delayed response to your issue. If you still are having issues with your IP address, the best thing to do would be to open a support ticket. There you can provide some more details, i.e. the service / app you are using.  the IP address in question and the data center.  There is no way I believe to verify without that information. Thanks!
