### ISSUE TITLE
Add 50.22.0.0/15

### ISSUE THREAD

**Issue by ynadji** [ibm-cloud-docs/cloud-infrastructure#18]
It seems `50.22.0.0/15` is "owned" by SoftLayer, which was acquired to be IBM cloud. Is it possible these, or a subset of these, should be included beyond the `50.22.118.0/23` that's already in this list?

```
$ whois 50.22.0.0/15
...
# whois.arin.net

NetRange:       50.22.0.0 - 50.23.255.255
CIDR:           50.22.0.0/15
NetName:        SOFTLAYER-4-9
NetHandle:      NET-50-22-0-0-1
Parent:         NET50 (NET-50-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       AS36351
Organization:   SoftLayer Technologies Inc. (SOFTL)
RegDate:        2010-11-01
Updated:        2013-07-12
Ref:            https://rdap.arin.net/registry/ip/50.22.0.0
...
```

**Comment by DLM-IBM** [comment]
Thank you for the comment. This issue is being investigated and will be resolved by the documentation team.

**Comment by Lauren-Fulcher** [comment]
@dprosper I looked through the ips.md page history, and found that the IP range 50.22.118.0/23 was deprecated/deleted from the page since April 2022: |dal07|Dallas|Texas|USA|50.22.118.0/23| was formerly and is no longer in the list. Do you think this fact resolves the issue?
