### ISSUE TITLE
Add a section how to access RackWare RMM UI

### ISSUE THREAD

**Issue by kyunghoryu** [ibm-cloud-docs/cloud-infrastructure#19]
It seems insufficient information regarding how to access RackWare RMM UI. This information needs to be added before "Option 2: Auto-provision" https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-migrating-on-prem-cloud-vpc#option-auto

This step is required for a user to access RackWare RMM that was deployed by Cloud Catalog.

To access RacWare RMM UI, please follow the steps below.

    Change password of admin user
        # passwd admin
    Open a WebBrower
        https://<ip address of the server>
        ID: admin
        Password: Entered above.

**Comment by DLM-IBM** [comment]
Thank you for the comment. This issue is being investigated and will be resolved by the documentation team.
