### ISSUE TITLE
Cloud Service Models diagram typo (should say "manages", not "messages")

### ISSUE THREAD

**Issue by abhattal** [ibm-cloud-docs/cloud-infrastructure#21]
On the "Understanding IaaS basics" page https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-getting-started-tutorial the the Cloud Service Models diagram should say "Client manages" not "Client messages" in the box at the far left ("on-premises" stack).

**Comment by DLM-IBM** [comment]
Thank you for the comment. This issue is being investigated and will be resolved by the documentation team.
