### ISSUE TITLE
Missing RHEL Server Requirements after Customer IP Range Test 

### ISSUE THREAD

**Issue by Ay1man2** [ibm-cloud-docs/cloud-infrastructure#26]
Hello, after working on a customer task for solidifying firewall IP range and Port requirements for Classic BM and VSI provisioning + Day 2 operations, my team has found the following requirements that are not listed on the IP Range documentation that support has deemed required for RHEL services. 

We tried to provision a BM on dal10, on a VLAN being protected by a vSRX Gateway, but the provisioning get stuck. We followed the documentation https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges#service-network. Also We followed https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges#red-hat-enterprise-linux-server.
We opened a Support Case CS2945812 cloud.ibm.com/unifiedsupport/cases/manage/CS2945812?accountId=cdefe6d99f7ea459aacb25775fb88a33

1. IBM Cloud support asked us to open the IP Range 10.2.232.0/24. We realized this is the SSL VPN network (on back-end/private network) for dal09(RHEL server requirements for dal10, the server were our BM is being provisioned, see https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges#red-hat-enterprise-linux-server). This information is not documented anywhere as a requirement for RHEL. The IP ranges for these SSL VPN requirements can be found SSL VPN Network section of the documentation, however there should be an indicator of its dependency for provisioning.

2. IBM Cloud support also found that the following RHEL endpoint is required to be opened for provisioning:
rhha01.updates.us-south.iaas.service.networklayer.com
• This requires adding the IP 161.26.112.28 to the firewall rules
• Since DNS round robin is involved, this endpoint is not a single endpoint and could be moved as needed.

Having said that, we think a client should be alert about this extra IP range is required during provisioning time of RHEL BM. It means a client should be able to provision a BM with the rules and ports described above. However, if support asks for any other IP required to be include on the Gateway rules, then that should be done to complete the provisioning of a BM.

3. One additional ask, is for an update on what the purpose for All TCP/UDP Ports being allowed should be for the service network, similar to ICMP being used for troubleshooting and monitoring: 

Ports to allow:
All TCP/UDP ports <needs to state the purpose here>
ICMP – ping (for support troubleshooting and monitoring)

If you would like to reference our JIRA issue on this task directly, please dm me on IBM slack @ayman.naji

**Comment by ssalerno-ibmcloud** [comment]
@Ay1man2 Adding a comment here - I'm not part of the doc team but do work in Cloud Support. The IP you referenced, 161.26.112.28 is covered if you included the appropriate ranges for dal13. The DAL13 Service Network list includes the subnet `161.26.112.0/22` which covers the IP specified.

Assuming the DAL10 and DAL12 have a DNS entry specific for those zones, they would be included in the subnets for those zones as well. Note also that this subnet needs to be routed over the private interface.

**Comment by Ay1man2** [comment]
@ssalerno-ibmcloud Sorry, I have updated my comment to provide more detailed information, as we should not be using dal13 for this customer task.

**Comment by Lauren-Fulcher** [comment]
Will investigate this further next week

**Comment by Lauren-Fulcher** [comment]
Staged edits, waiting for approval: https://github.ibm.com/cloud-docs/cloud-infrastructure/commit/a0ac0e2a188a030c09e97432fa32a62db677664d#diff-7c718e48848a0a9103e32595e5f8d8cf6d279773de524ba61b4459621b7cdb18

**Comment by Lauren-Fulcher** [comment]
Update from Stephen Ferguson: "I think the confusion here is that someone subdivided a lot of the networks in the article, and the entire 161.26.0.0 network used to be listed under ALL datacenters, so maybe whoever first put the requirements down for RHEL assumed that the entire 161.26 would already be allowed, so they didn't need to add that complexity to the article.. now that they are subdivided, the RHEL requirements to do need to change."

Checking in with red hat folks in another thread for guidance

**Comment by Ay1man2** [comment]
Thank you @Lauren-Fulcher!
