### ISSUE TITLE
Update Doc for Milan01 RHEL Range

### ISSUE THREAD

**Issue by ssalerno-ibmcloud** [ibm-cloud-docs/cloud-infrastructure#28]
Previously, MIL01 required opening the same ranges as FRA02 for RHEL purposes. This has apparently changed (Satellite got moved?) and the satellite is now in Fra04's subnet range. I've submitted PR #27 for correcting the table to reflect this.

**Comment by Lauren-Fulcher** [comment]
Thank you @ssalerno-ibmcloud! I'm looking into implementing the updates on PR #27 now.

**Comment by Lauren-Fulcher** [comment]
No change needed - confirmed in this message from my Slack chat with Steve Losh in the @iaas-redhat-operations channel:

Steve Losh
2 days ago
Hi @lfulcher. I've chatted with Steven Salerno about the issue and as I understand it, one of the IP ranges we provide to customers in the case they block outbound networking was somehow pointing to FRA04. Steven has submitted a pull request to have the correct range added to the the document that customers access to retrieve the list of IP ranges to add to their outbound firewall rules. Once the PR has been approved and merged to update the document, this should no longer be an issue.
