### ISSUE TITLE
IBM Cloud IP Ranges page doesn't list WSUS servers

### ISSUE THREAD

**Issue by delia-rusu** [ibm-cloud-docs/cloud-infrastructure#29]
### Detailed issue description

Topic (URL) with incorrect info: ---
https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges

What needs to be fixed: ---
We submitted feedback to the IBM Cloud page on IP ranges because the WSUS server IP address ranges are not documented on that page.

For tok04, the BCR addresses listed are 
10.3.17.0/24
10.192.0.0/16
10.201.187.0/24 
wsustok0401.service.softlayer.com is 10.201.177.200
wsustok0201.service.softlayer.com is 10.3.65.50
wsustok0501.service.softlayer.com is 10.201.193.200

We'd like to confirm that the WSUS servers should be included, and if so, they should be added.

--

### Additional details
We got customer feedback that the WSUS server IP range is not documented specific enough for a customer who only wants to open the bare minimum IP ranges in their firewall. Customers can find their WSUS server in the Windows registry by looking for the registry key documented on both of these Microsoft pages 
https://learn.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#configuring-automatic-updates-by-editing-the-registry
https://learn.microsoft.com/de-de/security-updates/windowsupdateservices/21669493

We’re not sure it’s appropriate to do a “Learn More” link and point to these Microsoft pages, but we’d like to somehow address the customer feedback to help them know specifics about where their WSUS server is.

We'd like to be able to tell customers with a firewall that they need to allow their Windows VSI access to WSUS, but we're having trouble knowing where to point them in IBM Cloud documentation.

**Comment by Lauren-Fulcher** [comment]
Hi @delia-rusu , I'll investigate this issue soon with a SME, thanks!

**Comment by dprosper** [comment]
see comment here: https://github.ibm.com/ibmcloud/docs-feedback-issues/issues/130#issuecomment-51276201

**Comment by Lauren-Fulcher** [comment]
Updates I made to ips.md: https://github.ibm.com/cloud-docs/cloud-infrastructure/commit/9d90d9b106aba047149fbaecafa920ce5aad234a#diff-7c718e48848a0a9103e32595e5f8d8cf6d279773de524ba61b4459621b7cdb18
