### ISSUE TITLE
Important section at the beginning list of Metrics available may be misleading?

### ISSUE THREAD

**Issue by ebcarty** [ibm-cloud-docs/cloud-infrastructure#3]
`The following metrics are available only if you use the IBM Cloud Monitoring with Sysdig full agent. If you provisioned a 'no driver mode' instance, see IBM Cloud Monitoring with Sysdig 'no driver mode' metrics.`

I believe platform metrics are available for the Cloud Service regardless of the agent type deployed.  Could we rephrase the wording so it doesn't give the impression that the platform metrics are only available with a sysdig full agent?

**Comment by gudrun-wolfgram** [comment]
Changed "are available only if you use" to "are associated with"
