### ISSUE TITLE
Not only 10.212.0.0/16 but also 10.44.0.0/16 is assigned to user's server in TOK02 BCR02.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/cloud-infrastructure#30]
https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges#service-network

Recently, TOK02 BCR02 has assigned 10.44.0.0/16 to user's server as well as 10.212.0.0/16.
Please add this information.
Best,

**Comment by Lauren-Fulcher** [comment]
Update: currently verifying the change with the IP Address registrar for Classic Cloud, David Brown, and his team Chris Turbeville and Krishna Tummala

**Comment by Lauren-Fulcher** [comment]
Update verified and completed
