### ISSUE TITLE
Broken link for: [IBM Cloud Design Decision Tool]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/cloud-infrastructure#35]
broken link for: [IBM Cloud Design Decision Tool](https://github.com/ibm-cloud-architecture/infrastructure-design-decision-tool)
https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-getting-started-tutorial

![image](https://user-images.githubusercontent.com/131889203/234646044-0a7af953-e206-48b2-aee9-2b4c422d084c.png)
![image](https://user-images.githubusercontent.com/131889203/234646064-66044292-3483-4784-89f3-5338b4924592.png)

**Comment by vickmuir** [comment]
Thank you for the comment. This issue is being investigated and will be resolved by the documentation team.
