### ISSUE TITLE
Broken link for: [IBM Cloud Design Decision Tool]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/cloud-infrastructure#36]
https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-planning-2

![image](https://user-images.githubusercontent.com/131889203/234646510-10138353-e1d6-4bc3-b18e-5b370f954737.png)
![image](https://user-images.githubusercontent.com/131889203/234646752-6503bb1c-1b59-4641-b5d8-4ed016dbc08d.png)

broken link for: [IBM Cloud Design Decision Tool](https://github.com/ibm-cloud-architecture/infrastructure-design-decision-tool/)

**Comment by vickmuir** [comment]
Thank you for the comment. This issue is being investigated and will be resolved by the documentation team.
