### ISSUE TITLE
Link Broken 

### ISSUE THREAD

**Issue by gaskinner84** [ibm-cloud-docs/cloud-infrastructure#38]
Good day! 
It appears the object storage link is broken on this page: 

https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-storage#storage

![image](https://github.com/ibm-cloud-docs/cloud-infrastructure/assets/46956547/9e4ee678-5eaf-4b93-a08c-b8dd55e9366a)

This link points to: https://cloud.ibm.com/docs/cloud-object-storagetopic=cloud-object-storage-getting-started-cloud-object-storage
It should point to: https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-getting-started-cloud-object-storage

Regards,

Gary S.
ACS-Storage Support Lead
IBM Cloud Support

**Comment by gudrun-wolfgram** [comment]
Thanks for letting us know about this broken link. The link for IBM Cloud Object Storage has been updated.
