### ISSUE TITLE
Serverless Service Outdated

### ISSUE THREAD

**Issue by heyfrancisco** [ibm-cloud-docs/cloud-infrastructure#39]
On the [Computer Services tab](https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-compute#serverless) the serverless options is outdated since **Functions Service** is deprecated, should be changed to **Code Engine**.

**Comment by amatetic** [comment]
the deprecated item is removed. Code Engine is already included in the doc.
