### ISSUE TITLE
Mention of incorrect location for 'OpenSSH' package for cygwin rsync installation

### ISSUE THREAD

**Issue by rahulippar** [ibm-cloud-docs/cloud-infrastructure#4]
Changes are required in following link
[Migrating data from IBM Cloud classic infrastructure to VPC
](https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-data-migration-classic-to-vpc
)
**Step 2: Install rsync** -> **Windows systems** -> **(5) Select OpenSSH (in shell category section).**
change "in **shell** category section" to "in **net** category section"

Same issue is mentioned by QE here with screenshots
https://github.ibm.com/workload-eng-services/diy-migration/issues/50

**Comment by Nicholas-Pierotti** [comment]
Requested changes have been made.

**Comment by Nicholas-Pierotti** [comment]
Do you want tis just pushed to draft, or also published?

**Comment by rahulippar** [comment]
Please publish changes whenever you are done.

**Comment by rahulippar** [comment]
Verified issue. So closing it.
