### ISSUE TITLE
Partially incorrect location for .ssh directory for linux

### ISSUE THREAD

**Issue by rahulippar** [ibm-cloud-docs/cloud-infrastructure#5]
Changes are required in following link
[Migrating data from IBM Cloud classic infrastructure to VPC](https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-data-migration-classic-to-vpc)

**Step 4: Generate SSH keys** -> **Linux systems** -> **(2)**

change "/home/**{username}**/.ssh" to "**{User's home directory}**/.ssh"
e.g. **/root/.ssh** for root user OR **/home/{username}/.ssh** for non-root user

**Comment by Nicholas-Pierotti** [comment]
Requested changes have been made

**Comment by Nicholas-Pierotti** [comment]
Do you want tis just pushed to draft, or also published?

**Comment by rahulippar** [comment]
Please publish changes whenever you are done.

**Comment by rahulippar** [comment]
Verified fix. So closing issue.
