### ISSUE TITLE
Partially incorrect location for authorized_keys in linux

### ISSUE THREAD

**Issue by rahulippar** [ibm-cloud-docs/cloud-infrastructure#6]
Changes are required in following link
[Migrating data from IBM Cloud classic infrastructure to VPC](https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-data-migration-classic-to-vpc)

**Step 4: Generate SSH keys** -> **Linux systems** -> **(3)**
Change "/home/**{username}/**.ssh/authorized_keys" to "**{user's home directory}/**.ssh/authorized_keys"
e.g. **/root/.ssh/authorized_keys** for root user OR **/home/{username}/.ssh/authorized_keys** for non-root user

**Comment by Nicholas-Pierotti** [comment]
Requested changes have been made.
 Do you want tis just pushed to draft, or also published?

**Comment by rahulippar** [comment]
Please publish changes whenever you are done.

**Comment by rahulippar** [comment]
Verified issue. So closing it.
