### ISSUE TITLE
Type 'CVS'

### ISSUE THREAD

**Issue by rahulippar** [ibm-cloud-docs/cloud-infrastructure#8]
Please fix typo 'CVS' to 'CSV'

https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-pv-migration-private-network
In 'Step 5: Set up RackWare RMM waves for P2V migration' section
Change has to be done In following sentence 
'If you are doing multiple, simultaneous migrations, download the **CVS** template from the RMM server and complete the appropriate fields.'

**Comment by gudrun-wolfgram** [comment]
Update complete.
